# Generates a header file with the weights for the model

# Run this script in the Software/ directory, and make sure the model is
# present in .csv format in the Weights/ directory.

lstm_dir = 'Weights/0_lstm/'
dense_dir = 'Weights/1_dense/'
input_size = 1
numUnits = 50

with open(lstm_dir + 'mergedW.csv') as file:
    lstm_w = ['{' + line.strip('\n') + '}' for line in file.readlines()]

with open(lstm_dir + 'b.csv') as file:
    lstm_b = '{' + file.read().strip('\n') + '}'

lstm_w = '{' + ','.join(lstm_w) + '}'

with open(dense_dir + 'weights.csv') as file:
    dense_w = '{' + file.read().strip('\n') + '}'

with open(dense_dir + 'bias.csv') as file:
    dense_b = file.read().strip('\n')

file_contents = f"""
// LSTM model header file
// Generated by gen_weight_header.py
#ifndef MODELWEIGHTS
#define MODELWEIGHTS

#define NUMUNITS {numUnits}
#define INPUTSIZE {input_size}

float lstmW[][{numUnits + input_size}] = {lstm_w};
float lstmB[] = {lstm_b};
float denseW[] = {dense_w};
float denseB = {dense_b};

#endif  // MODELWEIGHTS
"""
with open('Arduino Code/model-weights.h', 'w') as file:
    file.write(file_contents)
